services:
  - type: web
    name: meu-robo-whatsapp
    plan: free
    image:
      repository: evolutionapi/evolution-api
      tag: latest
    envVars:
      - key: AUTHENTICATION_TYPE
        value: apikey
      - key: AUTHENTICATION_API_KEY
        value: "246810"
      - key: TYPEBOT_ENABLED
        value: "true"
      - key: TYPEBOT_URL
        value: https://app.typebot.com
